/* Ordered structured-effect orchestration. Handlers delegate to the established combat adapters. */
var STRUCTURED_EFFECT_LEGACY_FALLBACKS = Object.create(null);
function warnLegacyEffectFallback(ability){ var id=ability&&ability.id||'<unknown>'; STRUCTURED_EFFECT_LEGACY_FALLBACKS[id]=(STRUCTURED_EFFECT_LEGACY_FALLBACKS[id]||0)+1; if(typeof console!=='undefined'&&console.warn)console.warn('[legacy-effect-parser] '+id+' used legacy description fallback.'); }
function parseLegacyAbilityToEffects(ability){ if(Avian.workbookEffects&&typeof Avian.workbookEffects.parseEffectClauses==='function')return Avian.workbookEffects.parseEffectClauses(ability.riderText||ability.legacyDescription||''); return []; }
function resolveAbilityEffects(ability){ if(ability&&Array.isArray(ability.effects)&&ability.effects.length){ var errors=validateSkill(ability); if(errors.length){ var error=new Error(errors.map(function(e){return e.message;}).join('\n')); error.validationErrors=errors; throw error; } return normalizeSkillEffects(ability); } warnLegacyEffectFallback(ability); return parseLegacyAbilityToEffects(ability||{}); }
function createEffectExecutionContext(context,ability){ return Object.assign({actor:null,target:null,ability:ability,sourceItem:null,hitResults:[],allHitsLanded:false,damageDealt:0,healthDamageDealt:0,armourDamageDealt:0,magicArmourDamageDealt:0,criticalOccurred:false,currentEffect:null,combatEnded:false,events:[]},context||{}); }
function effectTriggerMatches(effect,x){ if(effect.trigger==='onHealthDamage'||effect.trigger==='afterHealthDamage')return x.healthDamageDealt>0; if(effect.trigger==='afterAllHits')return !!x.allHitsLanded; return effect.trigger!=='nextMatchingSkill'; }
function effectConditionsPass(effect,x){ return !(effect.conditions||[]).some(function(c){ if(c.type==='armourBroken')return !!c.value!==!!(x.target&&x.target.stats&&x.target.stats.armour<=0); return false; }); }
function callStructuredAdapter(name,e,x){ var fn=x.adapters&&x.adapters[name]; if(typeof fn==='function')return fn(e,x); x.events.push({type:e.type,status:'delegated',effect:e}); }
function executeDamageEffect(e,x){return callStructuredAdapter('damage',e,x);} function executeApplyAilmentEffect(e,x){return callStructuredAdapter('applyAilment',e,x);} function executeRestoreProtectionEffect(e,x){return callStructuredAdapter('restoreProtection',e,x);} function executeTemporaryProtectionEffect(e,x){return callStructuredAdapter('temporaryProtection',e,x);} function executeModifyStatEffect(e,x){return callStructuredAdapter('modifyStat',e,x);} function executeChooseStatModifierEffect(e,x){return callStructuredAdapter('chooseStatModifier',e,x);} function executeCleanseEffect(e,x){return callStructuredAdapter('cleanse',e,x);} function executePenetrationEffect(e,x){return callStructuredAdapter('penetration',e,x);} function executeLifestealEffect(e,x){return callStructuredAdapter('lifesteal',e,x);} function executeModifyAilmentChanceEffect(e,x){return callStructuredAdapter('modifyAilmentChance',e,x);} function executeModifyStatusDurationEffect(e,x){return callStructuredAdapter('modifyStatusDuration',e,x);} function executeModifyNextStatusDurationEffect(e,x){return callStructuredAdapter('modifyNextStatusDuration',e,x);} function executeArmNextSkillEffect(e,x){return callStructuredAdapter('armNextSkill',e,x);} function executeResolveSourceRiderEffect(e,x){return callStructuredAdapter('resolveSourceRider',e,x);} function executeCustomLegacyEffect(e,x){return callStructuredAdapter('customLegacy',e,x);}
const EFFECT_HANDLERS={damage:executeDamageEffect,applyAilment:executeApplyAilmentEffect,restoreProtection:executeRestoreProtectionEffect,temporaryProtection:executeTemporaryProtectionEffect,modifyStat:executeModifyStatEffect,chooseStatModifier:executeChooseStatModifierEffect,cleanse:executeCleanseEffect,penetration:executePenetrationEffect,lifesteal:executeLifestealEffect,modifyAilmentChance:executeModifyAilmentChanceEffect,modifyStatusDuration:executeModifyStatusDurationEffect,modifyNextStatusDuration:executeModifyNextStatusDurationEffect,armNextSkill:executeArmNextSkillEffect,resolveSourceRider:executeResolveSourceRiderEffect,customLegacy:executeCustomLegacyEffect};
function executeStructuredEffect(e,x){x.currentEffect=e;return EFFECT_HANDLERS[e.type](e,x);} function finalizeEffectExecution(x){x.currentEffect=null;return x;} function executeStructuredAbility(context,ability){var effects=resolveAbilityEffects(ability),x=createEffectExecutionContext(context,ability);for(var i=0;i<effects.length;i++){if(!effectTriggerMatches(effects[i],x)||!effectConditionsPass(effects[i],x))continue;executeStructuredEffect(effects[i],x);if(x.combatEnded)break;}return finalizeEffectExecution(x);}
/* Bridge structured primary mechanics into the proven dispatcher row. */
function structuredSkillForRuntime(skill,item){if(skill&&skill.effects&&skill.effects.length)return skill;var all=Avian.data.structuredEffects&&Avian.data.structuredEffects.skills||[];if(item&&item.id)return all.find(function(s){return s.sourceId===item.id&&s.sourceSlot==='Basic Attack';})||skill;return skill;}
function applyStructuredEffectsToCombatRow(row,skill,item){skill=structuredSkillForRuntime(skill,item);if(!skill||!skill.effects||!skill.effects.length)return row;var effects=resolveAbilityEffects(skill),damage=effects.find(function(e){return e.type==='damage';}),ail=effects.find(function(e){return e.type==='applyAilment';});row.effects=effects;row.structuredSkillId=skill.id;row.structuredDescription=describeStructuredAbility(skill,{mode:'full'});row.riderText=row.structuredDescription;if(damage){row.skillPowerPct=damage.powerPercent;row.skillPower=damage.powerPercent/100;row.fixedCoefficient=row.skillPower;row.hits=row.hitCount=damage.hitCount||1;row.scalingStat=row.scaleStat=row.damageStat=({might:'ATK',dexterity:'DEX',focus:'MATK'}[damage.scalingStat]||row.scalingStat);row.damageType=damage.damageType==='magic'?'Magic':'Physical';}if(ail&&ail.ailmentId!=='sourceAilment'){row.ailment=ail.ailmentId;row.ailmentStacks=ail.stacks;row.ailmentChance=ail.chancePercent;row.ailmentRequireBothHitsHealth=ail.trigger==='afterAllHits';}return row;}
Avian.effects=Avian.effects||Object.create(null);Object.assign(Avian.effects,{handlers:EFFECT_HANDLERS,resolveAbilityEffects:resolveAbilityEffects,executeStructuredAbility:executeStructuredAbility,applyToCombatRow:applyStructuredEffectsToCombatRow,legacyFallbackAudit:STRUCTURED_EFFECT_LEGACY_FALLBACKS});
