# Avian Ascent — bundle builder (PowerShell port of scripts/build-bundle.js)
# Usage: .\scripts\build-bundle.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Manifest = Join-Path $Root 'js\bootstrap\load-order.json'
$Output = Join-Path $Root 'js\avian-game.bundle.js'
$Sw = Join-Path $Root 'sw.js'
$HashFile = Join-Path $Root 'js\avian-game.bundle.hash'

$manifestJson = Get-Content -Raw -Encoding UTF8 $Manifest | ConvertFrom-Json
$files = @($manifestJson.gameShellScripts)
if (-not $files -or $files.Count -eq 0) { throw 'load-order.json: gameShellScripts must be an array' }

$body = ''
$totalBytes = 0
foreach ($rel in $files) {
    $full = Join-Path $Root ($rel -replace '/', '\')
    if (-not (Test-Path $full)) { throw "Missing manifest entry: $rel" }
    $src = Get-Content -Raw -Encoding UTF8 $full
    $totalBytes += $src.Length
    $body += "`n;/* === $($rel -replace '\\','/') === */`n"
    $body += $src
}

$sha = [System.Security.Cryptography.SHA256]::Create()
$hashBytes = $sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($body))
$hash = ([BitConverter]::ToString($hashBytes) -replace '-','').ToLower().Substring(0, 12)

$header = @"
/* Avian Ascent — generated by scripts/build-bundle.ps1. Do not edit by hand.
 * Source order: js/bootstrap/load-order.json
 * Bundle hash:  $hash
 */
globalThis.__AVIAN_BUNDLE_HASH__ = "$hash";

"@

$outDir = Split-Path $Output -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($Output, $header + $body, [Text.Encoding]::UTF8)
[System.IO.File]::WriteAllText($HashFile, "$hash`n", [Text.Encoding]::UTF8)

if (Test-Path $Sw) {
    $swContent = Get-Content -Raw -Encoding UTF8 $Sw
    $next = $swContent -replace "const CACHE_VERSION = '[^']+';", "const CACHE_VERSION = 'avian-ascent-$hash';"
    if ($next -ne $swContent) { [System.IO.File]::WriteAllText($Sw, $next, [Text.Encoding]::UTF8) }
}

Write-Host "[bundle] wrote js/avian-game.bundle.js ($($files.Count) files, $([math]::Round($totalBytes/1024,1)) KiB source, hash $hash)"
