# Avian Ascent — bundle builder (PowerShell, no Node required)
# Concatenates js/bootstrap/load-order.json into js/avian-game.bundle.js

param(
    [switch]$Watch
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$Manifest = Join-Path $Root 'js\bootstrap\load-order.json'
$Output = Join-Path $Root 'js\avian-game.bundle.js'
$HashFile = Join-Path $Root 'js\avian-game.bundle.hash'
$SwPath = Join-Path $Root 'sw.js'

function Read-Manifest {
    $raw = Get-Content $Manifest -Raw | ConvertFrom-Json
    if ($raw.gameShellScripts) { return @($raw.gameShellScripts) }
    return @($raw)
}

function Rewrite-SwCacheVersion([string]$Hash) {
    if (-not (Test-Path $SwPath)) { return }
    $swText = Get-Content $SwPath -Raw
    $next = [regex]::Replace($swText, "const CACHE_VERSION = '[^']+';", "const CACHE_VERSION = 'avian-ascent-$Hash';")
    if ($next -ne $swText) { [System.IO.File]::WriteAllText($SwPath, $next, [Text.Encoding]::UTF8) }
}

function Build-Once {
    $start = Get-Date
    $files = Read-Manifest
    $body = ''
    $totalBytes = 0
    foreach ($rel in $files) {
        $full = Join-Path $Root ($rel -replace '/', '\')
        if (-not (Test-Path $full)) { throw "[bundle] missing manifest entry: $rel" }
        $src = [System.IO.File]::ReadAllText($full, [Text.Encoding]::UTF8)
        $totalBytes += $src.Length
        $norm = $rel -replace '\\', '/'
        $body += "`n;/* === $norm === */`n"
        $body += $src
    }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hashBytes = $sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($body))
    $hash = -join ($hashBytes[0..5] | ForEach-Object { $_.ToString('x2') })
    $header = @"
/* Avian Ascent - generated by scripts/build-bundle.ps1. Do not edit by hand.
 * Source order: js/bootstrap/load-order.json
 * Bundle hash:  $hash
 */
globalThis.__AVIAN_BUNDLE_HASH__ = "$hash";

"@
    [System.IO.File]::WriteAllText($Output, $header + $body, [Text.Encoding]::UTF8)
    [System.IO.File]::WriteAllText($HashFile, ($hash + [Environment]::NewLine), [Text.Encoding]::UTF8)
    Rewrite-SwCacheVersion $hash
    $ms = ((Get-Date) - $start).TotalMilliseconds
    $kib = [Math]::Round($totalBytes / 1024, 1)
    Write-Host "[bundle] wrote js/avian-game.bundle.js ($($files.Count) files, ${kib} KiB source, hash $hash) in $([Math]::Round($ms)) ms"
}

Build-Once
